import {
  Bot,
  Building,
  BarChart,
  Clock,
  CreditCard,
  Database,
  FileText,
  History,
  Home,
  Lightbulb,
  LogOut,
  MessageSquare,
  Mic,
  MicOff,
  MoreHorizontal,
  Plus,
  Search,
  Settings,
  LoaderPinwheelIcon as Spinner,
  Timer,
  TrendingUp,
  Unplug,
  User,
  Users,
  Zap,
  Activity,
  Book,
  Code,
  ChevronsUpDown,
  Volume2,
  Square,
  Shield,
  ExternalLink,
  Play,
  Check,
  X,
  ArrowLeft,
  ArrowRight,
  Upload,
  RefreshCw,
} from "lucide-react"

export const Icons = {
  bot: Bot,
  building: Building,
  barChart: BarChart,
  clock: Clock,
  creditCard: CreditCard,
  database: Database,
  fileText: FileText,
  history: History,
  home: Home,
  lightbulb: Lightbulb,
  logOut: LogOut,
  messageSquare: MessageSquare,
  mic: Mic,
  micOff: MicOff,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  search: Search,
  settings: Settings,
  spinner: Spinner,
  timer: Timer,
  trendingUp: TrendingUp,
  unplug: Unplug,
  user: User,
  users: Users,
  zap: Zap,
  activity: Activity,
  book: Book,
  code: Code,
  chevronsUpDown: ChevronsUpDown,
  // NEW EXPORTS
  volume2: Volume2,
  square: Square,
  shield: Shield,
  externalLink: ExternalLink,
  play: Play,
  check: Check,
  x: X,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  upload: Upload,
  refreshCw: RefreshCw,
}
